---
title: "Test"
output: html_document
---

```{r}
source("helpers/strategies.R")
source("helpers/plots.R")
```

```{r}
load("Dataset1/data1_2022_Q1.RData")
res_long <- get_pnl_ma(data1_2022_Q1$NQ,
    group = 1,
    slow_param = 30, fast_param = 10,
    p_val = 50, tr_cost = 12, add_info = TRUE
)
res_long

cbind(
get_statistics(res_long$pnl_gross_mm,res_long$pnl_net_mm),
get_statistics(res_long$pnl_gross_mr,res_long$pnl_net_mr),
get_statistics(res_long$pnl_gross_fl,res_long$pnl_net_fl))

plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = res_long$pos_fl,
    date = "2022-01-04"
)

plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = res_long$pos_mm,
    date = "2022-01-04"
)

plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = res_long$pos_mr,
    date = "2022-01-04"
)
res_short <- get_pnl_ma(data1_2022_Q1$NQ,
    group = 1,
    slow_param = 60, fast_param = 10,
    p_val = 50, tr_cost = 12, add_info = FALSE, add_stats = FALSE
)
res_short
```

```{r}
source("https://raw.githubusercontent.com/ptwojcik/HFD/master/functions_plotPositions.R")
res_vb <- get_pnl_vb(data1_2022_Q1$NQ, group = 1, 40, 10, 25, m_ = 1.5, p_val = 50, tr_cost = 12, add_info = TRUE, add_stats = FALSE)

res_vb <- get_pnl_vb(
    prices = data1_2022_Q1$NQ,
    group = 1,
    slow_param = 50,
    fast_param = 20,
    volat_param = 30,
    m_ = 1.5,
    p_val = 20,
    tr_cost = 12,
    signal_estimator = "median",
    window_regime = 20,
    treshold_regime = 0.2,
    add_info = TRUE,
    add_stats = FALSE)

res_short <- get_pnl_vb(
    prices = data1_2022_Q1$NQ,
    group = 1,
    slow_param = 50,
    fast_param = 20,
    volat_param = 30,
    m_ = 1.5,
    p_val = 20,
    tr_cost = 12,
    signal_estimator = "median",
    window_regime = 20,
    treshold_regime = 0.2,
    add_info = FALSE,
    add_stats = TRUE)

res_vb$upper <- res_vb$slow_m + 1.5 * res_vb$volat_sd
res_vb$lower <- res_vb$slow_m - 1.5 * res_vb$volat_sd

plotPositionsVB(
    data_plot = res_vb,
    date = "2022-01-04", col_signal = "fast_m", col_upper = "upper", col_lower = "lower", col_pos = "pos_fl",
    main = "", save_graph = FALSE, width = 12, height = 8, file_name = NULL
)
```

```{r}
# WYKRES PNL - ZROBIĆ ŁADNIEJSZY WYKRES
fast_ma_ <- 37
slow_ma_ <- fast_ma_ + 34

window_regime <- 20
treshold_regime <- 0.11715

volat_param <- 40

m_exit_ <- 1.95150
m_diff_ <- 1
m_entry_ <- m_exit_ + m_diff_


res_2vb <- get_pnl_2vb(prices = data1_2022_Q1$SP,
                       group = 1,
                       slow_param = slow_ma_,
                       fast_param = fast_ma_,
                       volat_param = volat_param,
                       m_entry = m_entry_,
                       m_exit = m_exit_,
                       p_val = 50,
                       tr_cost = 12,
                       signal_estimator = "mean",
                       window_regime = window_regime ,
                       treshold_regime = treshold_regime,
                       add_info = TRUE,
                       add_stats = FALSE)

res_2vb

plot(cumsum(res_2vb$pnl_gross_mm))
#KONIEC
maxdrawdown(cumsum(res_2vb$pnl_gross_mm))
maxdrawdown(cumsum(res_2vb$pnl_net_mm))

sum(is.na(res_2vb$pnl_net))
res_2vb$pnl_gross_mm
plot(cumsum(res_2vb$pnl_net_mm))
plot(cumsum(res_2vb$pnl_gross_mm))

all(res_2vb$pnl_gross_mm==0)
all(res_2vb$pnl_net_mm==0)


res_2vb$exit_lower <- res_2vb$slow_m - m_exit_ * res_2vb$volat_sd
res_2vb$exit_upper <- res_2vb$slow_m + m_exit_ * res_2vb$volat_sd
res_2vb$entry_lower <- res_2vb$slow_m - m_entry_ * res_2vb$volat_sd
res_2vb$entry_upper <- res_2vb$slow_m + m_entry_ * res_2vb$volat_sd

plot_2vb_ggplot(
    prices = res_2vb$prices,
    signal = res_2vb$fast_m,
    exit_lower = res_2vb$exit_lower,
    exit_upper = res_2vb$exit_upper,
    entry_lower = res_2vb$entry_lower,
    entry_upper = res_2vb$entry_upper,
    position = res_2vb$pos_fl,
    date = "2022-01-11"
)
```

```{r}
regime <- get_regime(prices = data1_2022_Q1$NQ, window = 14, treshold = 0., type = "corr")
corr_sign <- ifelse(corr_>0,1,-1)
plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = regime,
    date = "2022-03-23"
)
plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = corr_sign,
    date = "2022-03-24"
)

library(dygraphs)

corr_ <- runCor(y = lag.xts(data1_2022_Q1$NQ), x = lag.xts(data1_2022_Q1$NQ, 2), n = 100)
dygraph(merge(corr_,data1_2022_Q1$NQ)) %>%
  dySeries(
    name = "NQ",
    label = "Price",
    color = "black",
    axis = 'y',
    strokeWidth = 2,
    drawPoints = FALSE
  ) %>%
  dySeries(
    name = "corr_",
    label = "Correlation",
    color = "red",
    drawPoints = TRUE,
    pointSize = 4,
    strokeWidth = 0,
    axis = 'y2'
  ) %>%
  dyRangeSelector() %>%
  dyAxis('y', label = 'Price') %>%
  dyAxis('y2', label = 'Correlation') %>%
  dyOptions(connectSeparatedPoints = FALSE)

library(roll)
library(TTR)

RSI(lag.xts(data1_2022_Q1$NQ), n = 30)

long <- roll_var(log(lag.xts(data1_2022_Q1$NQ)), 50)
short <- roll_var(log(lag.xts(data1_2022_Q1$NQ)), 20)

cbind(short/long,data1_2022_Q1$NQ)['2022-01-04::2022-03-24'] %>%
  dygraph() %>%
  dySeries("NQ", label = "ratio", color = "red", axis = 'y', strokeWidth = 2, drawPoints = FALSE) %>%
dySeries("NQ.1", label = "price", color = "black", axis = 'y2', strokeWidth = 2, drawPoints = FALSE) %>%
  dyRangeSelector() %>%
  dyAxis('y', label = 'Price') %>%
  dyAxis('y2', label = 'Correlation') %>%
  dyOptions(connectSeparatedPoints = FALSE)

plot(cbind(long, short,data1_2022_Q1$NQ))

```

## 2VB

```{r}
fast_ma_ <- 37
slow_ma_ <- fast_ma_ + 34
window_regime <- 20
treshold_regime <- 0.11715
volat_param <- 40
m_exit_ <- 1.95150
m_diff_ <- 1
m_entry_ <- m_exit_ + m_diff_
signal_estimator <-"mean"

# XAU,2
stat_all<- c()

for (selected_quarter in c(
    "2022_Q1", "2022_Q3", "2022_Q4",
    "2023_Q2", "2023_Q4",
    "2024_Q1", "2024_Q2"
)) {
    message(selected_quarter)

    filename_ <- paste0("Dataset2/data2_", selected_quarter, ".RData")

    load(filename_)

    data.group2 <- get(paste0("data2_", selected_quarter))
    res_2vb <- get_pnl_2vb(
        prices = data.group2$XAU,
        group = 2,
        slow_param = slow_ma_,
        fast_param = fast_ma_,
        volat_param = volat_param,
        m_entry = m_entry_,
        m_exit = m_exit_,
        p_val = 100,
        tr_cost = 15,
        signal_estimator = signal_estimator,
        window_regime = window_regime,
        treshold_regime = treshold_regime,
        add_info = FALSE,
        add_stats = TRUE
    )
    
    stat_all<-rbind(stat_all,res_2vb)
}

stat_all
```

## VB

```{r}
fast_ma_ <- 37
slow_ma_ <- fast_ma_ + 34
window_regime <- 20
treshold_regime <- 0.11715
volat_param <- 40
m_ <- 1.95150
signal_estimator <- "mean"

# XAU,2
stat_all<- c()

for (selected_quarter in c(
    "2022_Q1", "2022_Q3", "2022_Q4",
    "2023_Q2", "2023_Q4",
    "2024_Q1", "2024_Q2"
)) {
    message(selected_quarter)

    filename_ <- paste0("Dataset2/data2_", selected_quarter, ".RData")

    load(filename_)

    data.group2 <- get(paste0("data2_", selected_quarter))
    res_vb <- get_pnl_vb(
        prices = data.group2$XAU,
        group = 2,
        slow_param = slow_ma_,
        fast_param = fast_ma_,
        volat_param = volat_param,
        m_ = m_,
        p_val = 100,
        tr_cost = 15,
        scale_ = 252,
        signal_estimator = signal_estimator,
        window_regime = window_regime,
        treshold_regime = treshold_regime,
        add_info = FALSE,
        add_stats = TRUE
    )
    
    stat_all2<-rbind(stat_all2,res_vb)
}

stat_all2
```

## MA

```{r}
fast_ma_ <- 37
slow_ma_ <- fast_ma_ + 34
window_regime <- 20
treshold_regime <- 0.11715
signal_estimator <- "mean"

# XAU,2
stat_all<- c()

for (selected_quarter in c(
    "2022_Q1", "2022_Q3", "2022_Q4",
    "2023_Q2", "2023_Q4",
    "2024_Q1", "2024_Q2"
)) {
    message(selected_quarter)

    filename_ <- paste0("Dataset2/data2_", selected_quarter, ".RData")

    load(filename_)

    data.group2 <- get(paste0("data2_", selected_quarter))
    res_ma <- get_pnl_ma(
        prices = data.group2$XAU,
        group = 2,
        slow_param = slow_ma_,
        fast_param = fast_ma_,
        p_val = 100,
        tr_cost = 15,
        scale_ = 252,
        signal_estimator = signal_estimator,
        window_regime = window_regime,
        treshold_regime = treshold_regime,
        add_info = FALSE,
        add_stats = TRUE
    )
    
    stat_all3<-rbind(stat_all3,res_ma)
}

stat_all3
```
## Wykresy PNL

### 2VB
```{r}
fast_ma_ <- 37
slow_ma_ <- fast_ma_ + 34
window_regime <- 20
treshold_regime <- 0.11715
volat_param <- 40
m_exit_ <- 1.95150
m_diff_ <- 1
m_entry_ <- m_exit_ + m_diff_
signal_estimator <-"mean"
res_2vb <- get_pnl_2vb(prices = data1_2022_Q1$SP,
                       group = 1,
                       slow_param = slow_ma_,
                       fast_param = fast_ma_,
                       volat_param = volat_param,
                       m_entry = m_entry_,
                       m_exit = m_exit_,
                       p_val = 50,
                       tr_cost = 12,
                       signal_estimator = signal_estimator,
                       window_regime = window_regime ,
                       treshold_regime = treshold_regime,
                       add_info = TRUE,
                       add_stats = FALSE)

res_2vb

plot(cumsum(res_2vb$pnl_gross_mm))
```


### VB
```{r}
fast_ma_ <- 37
slow_ma_ <- fast_ma_ + 34
window_regime <- 20
treshold_regime <- 0.11715
volat_param <- 40
m_ <- 1.95150
signal_estimator <- "mean"
res_vb <- get_pnl_vb(prices = data1_2022_Q1$SP,
                       group = 1,
                       slow_param = slow_ma_,
                       fast_param = fast_ma_,
                       volat_param = volat_param,
                       m_=m_,
                       p_val = 50,
                       tr_cost = 12,
                       signal_estimator = signal_estimator,
                       window_regime = window_regime ,
                       treshold_regime = treshold_regime,
                       add_info = TRUE,
                       add_stats = FALSE)

res_vb

plot(cumsum(res_vb$pnl_gross_mm))
```

### MA
```{r}
fast_ma_ <- 37
slow_ma_ <- fast_ma_ + 34
window_regime <- 20
treshold_regime <- 0.11715
signal_estimator <- "mean"
res_ma <- get_pnl_ma(prices = data1_2022_Q1$SP,
                       group = 1,
                       slow_param = slow_ma_,
                       fast_param = fast_ma_,
                       p_val = 50,
                       tr_cost = 12,
                       signal_estimator = signal_estimator,
                       window_regime = window_regime ,
                       treshold_regime = treshold_regime,
                       add_info = TRUE,
                       add_stats = FALSE)

res_vb

plot(cumsum(res_ma$pnl_gross_mm))
```
