---
title: "Test"
output: html_document
---

```{r}
source("helpers/strategies.R")
source("helpers/plots.R")
```

```{r}
load("Dataset1/data1_2022_Q1.RData")
res_long <- get_pnl_ma(data1_2022_Q1$NQ,
    group = 1,
    slow_param = 30, fast_param = 10,
    p_val = 50, tr_cost = 12, add_info = TRUE
)
res_long
plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = res_long$pos_fl,
    date = "2022-01-04"
)

plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = res_long$pos_mm,
    date = "2022-01-04"
)

plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = res_long$slow_m, fast_m = res_long$fast_m,
    position = res_long$pos_mr,
    date = "2022-01-04"
)
res_short <- get_pnl_ma(data1_2022_Q1$NQ,
    group = 1,
    slow_param = 60, fast_param = 10,
    p_val = 50, tr_cost = 12, add_info = FALSE
)
res_short
```

```{r}
source("https://raw.githubusercontent.com/ptwojcik/HFD/master/functions_plotPositions.R")
changes_sign_mean <- roll_mean(ifelse(diff.xts(data1_2022_Q1$NQ) > 0, 1, -1), 10)
regime <- ifelse(abs(changes_sign_mean) < 0.01, 0, ifelse(changes_sign_mean > 0.05, 1, -1))

plot_ma_ggplot(
    prices = res_long$prices,
    slow_m = 0, fast_m = 0,
    position = regime,
    date = "2022-01-04"
)

res_vb <- get_pnl_vb(data1_2022_Q1$NQ, group = 1, 40, 10, 25, m_ = 1.5, p_val = 50, tr_cost = 12, add_info = TRUE, add_stats = FALSE)
res_vb$upper <- res_vb$slow_m + 1.5 * res_vb$volat_sd
res_vb$lower <- res_vb$slow_m - 1.5 * res_vb$volat_sd

plotPositionsVB(
    data_plot = res_vb,
    date = "2022-01-04", col_signal = "fast_m", col_upper = "upper", col_lower = "lower", col_pos = "pos_mm",
    main = "", save_graph = FALSE, width = 12, height = 8, file_name = NULL
)
```

```{r}
res_vb
```